//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from f:/GitHubRepository/CSharpCompiler/Compiler/Grammar/LangX.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public partial class LangXParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, TYPE=5, ADD=6, SUB=7, MUL=8, DIV=9, STRING=10, 
		WRITE=11, READ=12, ID=13, INT=14, FLOAT=15, NEWLINE=16, WS=17;
	public const int
		RULE_start = 0, RULE_stat = 1, RULE_assign = 2, RULE_reassign = 3, RULE_write = 4, 
		RULE_read = 5, RULE_expr0 = 6, RULE_op1 = 7, RULE_expr1 = 8, RULE_op2 = 9, 
		RULE_expr2 = 10;
	public static readonly string[] ruleNames = {
		"start", "stat", "assign", "reassign", "write", "read", "expr0", "op1", 
		"expr1", "op2", "expr2"
	};

	private static readonly string[] _LiteralNames = {
		null, "';'", "'='", "'('", "')'", null, "'+'", "'-'", "'*'", "'/'", null, 
		"'write'", "'read'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, "TYPE", "ADD", "SUB", "MUL", "DIV", "STRING", 
		"WRITE", "READ", "ID", "INT", "FLOAT", "NEWLINE", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "LangX.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static LangXParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public LangXParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public LangXParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class StartContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] NEWLINE() { return GetTokens(LangXParser.NEWLINE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NEWLINE(int i) {
			return GetToken(LangXParser.NEWLINE, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatContext[] stat() {
			return GetRuleContexts<StatContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatContext stat(int i) {
			return GetRuleContext<StatContext>(i);
		}
		public StartContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_start; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILangXListener typedListener = listener as ILangXListener;
			if (typedListener != null) typedListener.EnterStart(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILangXListener typedListener = listener as ILangXListener;
			if (typedListener != null) typedListener.ExitStart(this);
		}
	}

	[RuleVersion(0)]
	public StartContext start() {
		StartContext _localctx = new StartContext(Context, State);
		EnterRule(_localctx, 0, RULE_start);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 29;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 6178L) != 0)) {
				{
				{
				State = 23;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 6176L) != 0)) {
					{
					State = 22;
					stat();
					}
				}

				State = 25;
				Match(T__0);
				State = 26;
				Match(NEWLINE);
				}
				}
				State = 31;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public AssignContext assign() {
			return GetRuleContext<AssignContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public WriteContext write() {
			return GetRuleContext<WriteContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ReadContext read() {
			return GetRuleContext<ReadContext>(0);
		}
		public StatContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_stat; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILangXListener typedListener = listener as ILangXListener;
			if (typedListener != null) typedListener.EnterStat(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILangXListener typedListener = listener as ILangXListener;
			if (typedListener != null) typedListener.ExitStat(this);
		}
	}

	[RuleVersion(0)]
	public StatContext stat() {
		StatContext _localctx = new StatContext(Context, State);
		EnterRule(_localctx, 2, RULE_stat);
		try {
			State = 35;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case TYPE:
				EnterOuterAlt(_localctx, 1);
				{
				State = 32;
				assign();
				}
				break;
			case WRITE:
				EnterOuterAlt(_localctx, 2);
				{
				State = 33;
				write();
				}
				break;
			case READ:
				EnterOuterAlt(_localctx, 3);
				{
				State = 34;
				read();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AssignContext : ParserRuleContext {
		public AssignContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_assign; } }
	 
		public AssignContext() { }
		public virtual void CopyFrom(AssignContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class ExprContext : AssignContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TYPE() { return GetToken(LangXParser.TYPE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(LangXParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Expr0Context expr0() {
			return GetRuleContext<Expr0Context>(0);
		}
		public ExprContext(AssignContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILangXListener typedListener = listener as ILangXListener;
			if (typedListener != null) typedListener.EnterExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILangXListener typedListener = listener as ILangXListener;
			if (typedListener != null) typedListener.ExitExpr(this);
		}
	}

	[RuleVersion(0)]
	public AssignContext assign() {
		AssignContext _localctx = new AssignContext(Context, State);
		EnterRule(_localctx, 4, RULE_assign);
		try {
			_localctx = new ExprContext(_localctx);
			EnterOuterAlt(_localctx, 1);
			{
			State = 37;
			Match(TYPE);
			State = 38;
			Match(ID);
			State = 39;
			Match(T__1);
			State = 40;
			expr0();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ReassignContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(LangXParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Expr0Context expr0() {
			return GetRuleContext<Expr0Context>(0);
		}
		public ReassignContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_reassign; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILangXListener typedListener = listener as ILangXListener;
			if (typedListener != null) typedListener.EnterReassign(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILangXListener typedListener = listener as ILangXListener;
			if (typedListener != null) typedListener.ExitReassign(this);
		}
	}

	[RuleVersion(0)]
	public ReassignContext reassign() {
		ReassignContext _localctx = new ReassignContext(Context, State);
		EnterRule(_localctx, 6, RULE_reassign);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 42;
			Match(ID);
			State = 43;
			Match(T__1);
			State = 44;
			expr0();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class WriteContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WRITE() { return GetToken(LangXParser.WRITE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Expr0Context expr0() {
			return GetRuleContext<Expr0Context>(0);
		}
		public WriteContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_write; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILangXListener typedListener = listener as ILangXListener;
			if (typedListener != null) typedListener.EnterWrite(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILangXListener typedListener = listener as ILangXListener;
			if (typedListener != null) typedListener.ExitWrite(this);
		}
	}

	[RuleVersion(0)]
	public WriteContext write() {
		WriteContext _localctx = new WriteContext(Context, State);
		EnterRule(_localctx, 8, RULE_write);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 46;
			Match(WRITE);
			State = 47;
			expr0();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ReadContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode READ() { return GetToken(LangXParser.READ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(LangXParser.ID, 0); }
		public ReadContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_read; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILangXListener typedListener = listener as ILangXListener;
			if (typedListener != null) typedListener.EnterRead(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILangXListener typedListener = listener as ILangXListener;
			if (typedListener != null) typedListener.ExitRead(this);
		}
	}

	[RuleVersion(0)]
	public ReadContext read() {
		ReadContext _localctx = new ReadContext(Context, State);
		EnterRule(_localctx, 10, RULE_read);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 49;
			Match(READ);
			State = 50;
			Match(ID);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Expr0Context : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Expr1Context expr1() {
			return GetRuleContext<Expr1Context>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Op1Context[] op1() {
			return GetRuleContexts<Op1Context>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Op1Context op1(int i) {
			return GetRuleContext<Op1Context>(i);
		}
		public Expr0Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expr0; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILangXListener typedListener = listener as ILangXListener;
			if (typedListener != null) typedListener.EnterExpr0(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILangXListener typedListener = listener as ILangXListener;
			if (typedListener != null) typedListener.ExitExpr0(this);
		}
	}

	[RuleVersion(0)]
	public Expr0Context expr0() {
		Expr0Context _localctx = new Expr0Context(Context, State);
		EnterRule(_localctx, 12, RULE_expr0);
		int _la;
		try {
			State = 60;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,4,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 52;
				expr1();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 53;
				expr1();
				State = 57;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==ADD || _la==SUB) {
					{
					{
					State = 54;
					op1();
					}
					}
					State = 59;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Op1Context : ParserRuleContext {
		public Op1Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_op1; } }
	 
		public Op1Context() { }
		public virtual void CopyFrom(Op1Context context) {
			base.CopyFrom(context);
		}
	}
	public partial class AddContext : Op1Context {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ADD() { return GetToken(LangXParser.ADD, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Expr1Context expr1() {
			return GetRuleContext<Expr1Context>(0);
		}
		public AddContext(Op1Context context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILangXListener typedListener = listener as ILangXListener;
			if (typedListener != null) typedListener.EnterAdd(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILangXListener typedListener = listener as ILangXListener;
			if (typedListener != null) typedListener.ExitAdd(this);
		}
	}
	public partial class SubContext : Op1Context {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SUB() { return GetToken(LangXParser.SUB, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Expr1Context expr1() {
			return GetRuleContext<Expr1Context>(0);
		}
		public SubContext(Op1Context context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILangXListener typedListener = listener as ILangXListener;
			if (typedListener != null) typedListener.EnterSub(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILangXListener typedListener = listener as ILangXListener;
			if (typedListener != null) typedListener.ExitSub(this);
		}
	}

	[RuleVersion(0)]
	public Op1Context op1() {
		Op1Context _localctx = new Op1Context(Context, State);
		EnterRule(_localctx, 14, RULE_op1);
		try {
			State = 66;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case ADD:
				_localctx = new AddContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 62;
				Match(ADD);
				State = 63;
				expr1();
				}
				break;
			case SUB:
				_localctx = new SubContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 64;
				Match(SUB);
				State = 65;
				expr1();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Expr1Context : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Expr2Context expr2() {
			return GetRuleContext<Expr2Context>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Op2Context[] op2() {
			return GetRuleContexts<Op2Context>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Op2Context op2(int i) {
			return GetRuleContext<Op2Context>(i);
		}
		public Expr1Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expr1; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILangXListener typedListener = listener as ILangXListener;
			if (typedListener != null) typedListener.EnterExpr1(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILangXListener typedListener = listener as ILangXListener;
			if (typedListener != null) typedListener.ExitExpr1(this);
		}
	}

	[RuleVersion(0)]
	public Expr1Context expr1() {
		Expr1Context _localctx = new Expr1Context(Context, State);
		EnterRule(_localctx, 16, RULE_expr1);
		int _la;
		try {
			State = 76;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,7,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 68;
				expr2();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 69;
				expr2();
				State = 73;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==MUL || _la==DIV) {
					{
					{
					State = 70;
					op2();
					}
					}
					State = 75;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Op2Context : ParserRuleContext {
		public Op2Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_op2; } }
	 
		public Op2Context() { }
		public virtual void CopyFrom(Op2Context context) {
			base.CopyFrom(context);
		}
	}
	public partial class DivContext : Op2Context {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DIV() { return GetToken(LangXParser.DIV, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Expr2Context expr2() {
			return GetRuleContext<Expr2Context>(0);
		}
		public DivContext(Op2Context context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILangXListener typedListener = listener as ILangXListener;
			if (typedListener != null) typedListener.EnterDiv(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILangXListener typedListener = listener as ILangXListener;
			if (typedListener != null) typedListener.ExitDiv(this);
		}
	}
	public partial class MulContext : Op2Context {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MUL() { return GetToken(LangXParser.MUL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Expr2Context expr2() {
			return GetRuleContext<Expr2Context>(0);
		}
		public MulContext(Op2Context context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILangXListener typedListener = listener as ILangXListener;
			if (typedListener != null) typedListener.EnterMul(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILangXListener typedListener = listener as ILangXListener;
			if (typedListener != null) typedListener.ExitMul(this);
		}
	}

	[RuleVersion(0)]
	public Op2Context op2() {
		Op2Context _localctx = new Op2Context(Context, State);
		EnterRule(_localctx, 18, RULE_op2);
		try {
			State = 82;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case MUL:
				_localctx = new MulContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 78;
				Match(MUL);
				State = 79;
				expr2();
				}
				break;
			case DIV:
				_localctx = new DivContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 80;
				Match(DIV);
				State = 81;
				expr2();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Expr2Context : ParserRuleContext {
		public Expr2Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expr2; } }
	 
		public Expr2Context() { }
		public virtual void CopyFrom(Expr2Context context) {
			base.CopyFrom(context);
		}
	}
	public partial class StringContext : Expr2Context {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(LangXParser.STRING, 0); }
		public StringContext(Expr2Context context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILangXListener typedListener = listener as ILangXListener;
			if (typedListener != null) typedListener.EnterString(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILangXListener typedListener = listener as ILangXListener;
			if (typedListener != null) typedListener.ExitString(this);
		}
	}
	public partial class IdContext : Expr2Context {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(LangXParser.ID, 0); }
		public IdContext(Expr2Context context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILangXListener typedListener = listener as ILangXListener;
			if (typedListener != null) typedListener.EnterId(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILangXListener typedListener = listener as ILangXListener;
			if (typedListener != null) typedListener.ExitId(this);
		}
	}
	public partial class ExprInParensContext : Expr2Context {
		[System.Diagnostics.DebuggerNonUserCode] public Expr0Context expr0() {
			return GetRuleContext<Expr0Context>(0);
		}
		public ExprInParensContext(Expr2Context context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILangXListener typedListener = listener as ILangXListener;
			if (typedListener != null) typedListener.EnterExprInParens(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILangXListener typedListener = listener as ILangXListener;
			if (typedListener != null) typedListener.ExitExprInParens(this);
		}
	}
	public partial class FloatContext : Expr2Context {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FLOAT() { return GetToken(LangXParser.FLOAT, 0); }
		public FloatContext(Expr2Context context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILangXListener typedListener = listener as ILangXListener;
			if (typedListener != null) typedListener.EnterFloat(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILangXListener typedListener = listener as ILangXListener;
			if (typedListener != null) typedListener.ExitFloat(this);
		}
	}
	public partial class IntContext : Expr2Context {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT() { return GetToken(LangXParser.INT, 0); }
		public IntContext(Expr2Context context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILangXListener typedListener = listener as ILangXListener;
			if (typedListener != null) typedListener.EnterInt(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILangXListener typedListener = listener as ILangXListener;
			if (typedListener != null) typedListener.ExitInt(this);
		}
	}

	[RuleVersion(0)]
	public Expr2Context expr2() {
		Expr2Context _localctx = new Expr2Context(Context, State);
		EnterRule(_localctx, 20, RULE_expr2);
		try {
			State = 92;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case INT:
				_localctx = new IntContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 84;
				Match(INT);
				}
				break;
			case FLOAT:
				_localctx = new FloatContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 85;
				Match(FLOAT);
				}
				break;
			case ID:
				_localctx = new IdContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 86;
				Match(ID);
				}
				break;
			case STRING:
				_localctx = new StringContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 87;
				Match(STRING);
				}
				break;
			case T__2:
				_localctx = new ExprInParensContext(_localctx);
				EnterOuterAlt(_localctx, 5);
				{
				State = 88;
				Match(T__2);
				State = 89;
				expr0();
				State = 90;
				Match(T__3);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static int[] _serializedATN = {
		4,1,17,95,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,1,0,3,0,24,8,0,1,0,1,0,5,0,28,8,0,10,0,12,
		0,31,9,0,1,1,1,1,1,1,3,1,36,8,1,1,2,1,2,1,2,1,2,1,2,1,3,1,3,1,3,1,3,1,
		4,1,4,1,4,1,5,1,5,1,5,1,6,1,6,1,6,5,6,56,8,6,10,6,12,6,59,9,6,3,6,61,8,
		6,1,7,1,7,1,7,1,7,3,7,67,8,7,1,8,1,8,1,8,5,8,72,8,8,10,8,12,8,75,9,8,3,
		8,77,8,8,1,9,1,9,1,9,1,9,3,9,83,8,9,1,10,1,10,1,10,1,10,1,10,1,10,1,10,
		1,10,3,10,93,8,10,1,10,0,0,11,0,2,4,6,8,10,12,14,16,18,20,0,0,97,0,29,
		1,0,0,0,2,35,1,0,0,0,4,37,1,0,0,0,6,42,1,0,0,0,8,46,1,0,0,0,10,49,1,0,
		0,0,12,60,1,0,0,0,14,66,1,0,0,0,16,76,1,0,0,0,18,82,1,0,0,0,20,92,1,0,
		0,0,22,24,3,2,1,0,23,22,1,0,0,0,23,24,1,0,0,0,24,25,1,0,0,0,25,26,5,1,
		0,0,26,28,5,16,0,0,27,23,1,0,0,0,28,31,1,0,0,0,29,27,1,0,0,0,29,30,1,0,
		0,0,30,1,1,0,0,0,31,29,1,0,0,0,32,36,3,4,2,0,33,36,3,8,4,0,34,36,3,10,
		5,0,35,32,1,0,0,0,35,33,1,0,0,0,35,34,1,0,0,0,36,3,1,0,0,0,37,38,5,5,0,
		0,38,39,5,13,0,0,39,40,5,2,0,0,40,41,3,12,6,0,41,5,1,0,0,0,42,43,5,13,
		0,0,43,44,5,2,0,0,44,45,3,12,6,0,45,7,1,0,0,0,46,47,5,11,0,0,47,48,3,12,
		6,0,48,9,1,0,0,0,49,50,5,12,0,0,50,51,5,13,0,0,51,11,1,0,0,0,52,61,3,16,
		8,0,53,57,3,16,8,0,54,56,3,14,7,0,55,54,1,0,0,0,56,59,1,0,0,0,57,55,1,
		0,0,0,57,58,1,0,0,0,58,61,1,0,0,0,59,57,1,0,0,0,60,52,1,0,0,0,60,53,1,
		0,0,0,61,13,1,0,0,0,62,63,5,6,0,0,63,67,3,16,8,0,64,65,5,7,0,0,65,67,3,
		16,8,0,66,62,1,0,0,0,66,64,1,0,0,0,67,15,1,0,0,0,68,77,3,20,10,0,69,73,
		3,20,10,0,70,72,3,18,9,0,71,70,1,0,0,0,72,75,1,0,0,0,73,71,1,0,0,0,73,
		74,1,0,0,0,74,77,1,0,0,0,75,73,1,0,0,0,76,68,1,0,0,0,76,69,1,0,0,0,77,
		17,1,0,0,0,78,79,5,8,0,0,79,83,3,20,10,0,80,81,5,9,0,0,81,83,3,20,10,0,
		82,78,1,0,0,0,82,80,1,0,0,0,83,19,1,0,0,0,84,93,5,14,0,0,85,93,5,15,0,
		0,86,93,5,13,0,0,87,93,5,10,0,0,88,89,5,3,0,0,89,90,3,12,6,0,90,91,5,4,
		0,0,91,93,1,0,0,0,92,84,1,0,0,0,92,85,1,0,0,0,92,86,1,0,0,0,92,87,1,0,
		0,0,92,88,1,0,0,0,93,21,1,0,0,0,10,23,29,35,57,60,66,73,76,82,92
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
